### PR TITLE
chore: stub out a few wordwrap tests

### PR DESCRIPTION
**Pull request by meowgorithm**

### CODE REVIEW

**Comment by muesli** [comment]
I think this test belongs to the library that implements the functionality.

**Comment by meowgorithm** [comment]
Ah, you're probably right, though I do wonder if we want both, since Lip Gloss adds trailing spaces to build blocks.

```go
str := lipgloss.NewStyle().Width(10).Render("Hello, Kätzchen")
// Hello,••••
// Kätzchen••
```

**Comment by muesli** [comment]
> Ah, you're probably right, though I do wonder if we want both, since Lip Gloss adds trailing spaces to build blocks.

That's a good point, even though we're technically not testing the wrapping then, but padding the individual lines. Maybe just a slight misnomer then, even tho wrapping is involved.

**Comment by meowgorithm** [comment]
Okay, great point. I'll close the PR.

**Pull request closed without merging**
