### PR TITLE
feat: use tree enumerators

### PR DESCRIPTION
**Pull request by bashbunni**
- **feat: add Root option for lists**
- **refactor: use tree enumerators**

When a list is used as the root of a list, it merges the items and inherits the name of the root list. Otherwise it looks like the sub-list belongs to the last element in the root list.

e.g. 
image
> This but imagine the "More Documents", etc are indented

Instead it looks like
image

Where the root tree's items are appended to the end of the list

### CODE REVIEW

**Comment by bashbunni** [comment]
Builds off of the other PR that adds the `Title` func to set a name for the list

**Comment by meowgorithm** [comment]
Looking good. Want to merge this with #339 so we can treat this as a general pass over `tree`/`list`? I think it'll be easier to reason about that way.

**Review by caarlos0 — APPROVED** [review]

**Comment by bashbunni** [comment]
I think we should have the `Indenter` default to `TreeIndenter` when we set the Enumerator to `list.Tree` or `list.RoundedTree`. It feels weird having to specify that every time

**Comment by maaslalani** [comment]
Agreed!

**Comment by bashbunni** [comment]
🌴

**Comment by bashbunni** [comment]
Closing in favour of bringing trees out of internal https://github.com/charmbracelet/lipgloss/pull/342

**Pull request closed without merging**
